import type { Project } from "./api"

function addProjectMeta(p: Omit<Project, "completedAt" | "technologies" | "longDescription">): Project {
  return {
    ...p,
    completedAt: new Date().toISOString(),
    technologies: [],
    longDescription: p.description,
  }
}

export const projects: Project[] = [
  addProjectMeta({
    id: "end-to-end-insurance-risk-analytics",
    title: "End to End Insurance Risk Analytics Predictive Model",
    description: "Full-stack ML pipeline for insurance risk assessment with predictive modeling and analytics dashboards.",
    category: "AI/ML",
    imageUrl: "/End to End Insurance Risk Analytics Predictive Model.png",
    githubUrl: "https://github.com/dnNatnael/End-to-End-Insurance-Risk-Analytics-Predictive-Modeling",
    featured: true,
  }),
  addProjectMeta({
    id: "credit-risk-probability-model",
    title: "Credit Risk Probability Model for Alternative Data",
    description: "ML model using alternative data sources to predict credit risk and probability of default.",
    category: "AI/ML",
    imageUrl: "/Credit Risk Probability Mode for Alternative Data.png",
    githubUrl: "https://github.com/dnNatnael/Credit-Risk-Probability-Model-for-Alternative-Data",
  }),
  addProjectMeta({
    id: "solar-challenge",
    title: "Solar Challenge",
    description: "Data-driven solar energy prediction and optimization challenge project.",
    category: "AI/ML",
    imageUrl: "/Solar Challenge.png",
    githubUrl: "https://github.com/dnNatnael/solar-challenge-week0",
  }),
  addProjectMeta({
    id: "customer-experience-fintech",
    title: "Customer Experience for Fintech Apps",
    description: "Analytics and ML models to measure and improve customer experience in fintech applications.",
    category: "AI/ML",
    imageUrl: "/Customer Experience for Fintech Apps.png",
    githubUrl: "https://github.com/dnNatnael/Customer-Experience-Analytics-for-Fintech-Apps",
  }),
  addProjectMeta({
    id: "project-chimera",
    title: "Project Chimera",
    description: "AI/ML experiment combining multiple models for enhanced predictive capabilities.",
    category: "AI/ML",
    imageUrl: "/Project Chimera.png",
    githubUrl: "https://github.com/dnNatnael/project-chimera",
  }),
  addProjectMeta({
    id: "time-series-portfolio-optimization",
    title: "Time Series Forecasting for Portfolio Management Optimization",
    description: "Time series models and forecasting for optimizing investment portfolio allocation.",
    category: "AI/ML",
    imageUrl: "/Time Series Forecasting for Portfolio Optimization.png",
    githubUrl: "https://github.com/dnNatnael/time-series-forecasting-for-portfolio-management-optimization",
  }),
  addProjectMeta({
    id: "forecasting-financial-inclusion",
    title: "Forecasting Financial Inclusion in Ethiopia",
    description: "Predictive analytics for forecasting financial inclusion trends in Ethiopia.",
    category: "AI/ML",
    imageUrl: "/Forecasting Financial Inclusion in Ethiopia.png",
    githubUrl: "https://github.com/dnNatnael/Forecasting-Financial-Inclusion-in-Ethiopia",
  }),
  addProjectMeta({
    id: "intelligent-compliant-analysis",
    title: "Intelligent Compliant Analysis for Financial Services",
    description: "NLP and ML pipeline for automated compliance document analysis in finance.",
    category: "AI/ML",
    imageUrl: "/Intelligent Compliant Analysis for Fintech Services.png",
    githubUrl: "https://github.com/dnNatnael/intelligent-compliant-analysis-for-financial-services",
  }),
  addProjectMeta({
    id: "shipping-a-data-product",
    title: "Shipping a Data Product",
    description: "End-to-end data product pipeline from ingestion to deployment.",
    category: "AI/ML",
    imageUrl: "/Shipping a Data Product.png",
    githubUrl: "https://github.com/dnNatnael/Shipping-a-Data-Product",
  }),
  addProjectMeta({
    id: "predicting-price-moves-sentiment",
    title: "Predicting Price Moves with News Sentiment",
    description: "Sentiment analysis on news feeds to predict market price movements.",
    category: "AI/ML",
    imageUrl: "/Predicting Price Moves with News Sentiment.png",
    githubUrl: "https://github.com/dnNatnael/Predicting-Price-Moves-with-News-Sentiment",
  }),
  addProjectMeta({
    id: "change-point-analysis",
    title: "Change Point Analysis and Statistical Modeling",
    description: "Statistical modeling and change point detection for time series data.",
    category: "AI/ML",
    imageUrl: "/Change Point Analysis and Statistical Modeling.png",
    githubUrl: "https://github.com/dnNatnael/Change-Point-Analysis-and-Statistical-Modeling-of-Time-Series-Data",
  }),
  addProjectMeta({
    id: "fraud-detection-ecommerce",
    title: "Improved Detection of Fraud Cases for E-Commerce and Bank Transactions",
    description: "ML-based fraud detection system for e-commerce and banking transaction monitoring.",
    category: "AI/ML",
    imageUrl: "/ecommerce-dashboard-with-products.jpg",
    githubUrl: "https://github.com/dnNatnael/improved-detection-of-fraud-cases-for-e-commerce-and-bank-transactions",
  }),
  addProjectMeta({
    id: "barcode-scanner-location-tracker",
    title: "Barcode Scanner and Location Tracker Web Application",
    description: "Full-stack web app for scanning barcodes and tracking inventory with location services.",
    category: "Full-Stack",
    imageUrl: "/Barcode Scanner and Location Tracker.png",
    githubUrl: "https://github.com/dnNatnael/barcode-scanner-and-location-tracker-web-application",
    featured: true,
  }),
  addProjectMeta({
    id: "natnael-portfolio",
    title: "Natnael Portfolio",
    description: "Personal portfolio website built with Next.js, showcasing projects and skills.",
    category: "Full-Stack",
    imageUrl: "/Natnael Portfolio.png",
    githubUrl: "https://github.com/dnNatnael/natnael-portfolio",
    featured: true,
  }),
  addProjectMeta({
    id: "personal-profile",
    title: "Personal Profile",
    description: "Clean, responsive personal profile page with custom CSS styling.",
    category: "Frontend",
    imageUrl: "/Personal Profile.png",
    githubUrl: "https://github.com/dnNatnael/CSEC_DEV_Personal_Profile_with_CSS",
  }),
  addProjectMeta({
    id: "todo-list-app",
    title: "Todo List App",
    description: "Interactive todo list application with add, complete, and manage task features.",
    category: "Frontend",
    imageUrl: "/Todo List App.png",
    githubUrl: "https://github.com/dnNatnael/Todo-List-App",
  }),
]
